drop database if exists MUSEO;
create database MUSEO;
CREATE TABLE IF NOT EXISTS ESTILOS (
    codEstilo VARCHAR(30) NOT NULL,
    descripcion VARCHAR(100) NULL,
    CONSTRAINT PK_ESTILOS PRIMARY KEY (codEstilo)
);

CREATE TABLE IF NOT EXISTS ARTISTAS (
    codArtista VARCHAR(30) NOT NULL,
    nomArtista VARCHAR(60) NOT NULL,
    fecNaciArtista DATETIME NOT NULL,
    CONSTRAINT PK_ARTISTAS PRIMARY KEY (codArtista)
);

CREATE TABLE IF NOT EXISTS TIPOoBRAS (
    codTipoO VARCHAR(30) NOT NULL,
    descripcionTipo VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOoBRAS PRIMARY KEY (codTipoO)
);

CREATE TABLE IF NOT EXISTS SALAS (
    codSala VARCHAR(30) NOT NULL,
    nomSala VARCHAR(60) NOT NULL,
    descripcionS VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SALAS PRIMARY KEY (codSala)
);

CREATE TABLE IF NOT EXISTS OBRAS (
    codEstilo VARCHAR(30) NOT NULL,
    codArtista VARCHAR(30) NOT NULL,
    codTipoO VARCHAR(30) NOT NULL,
    codSala VARCHAR(30) NOT NULL,
    codObra VARCHAR(30) NOT NULL,
    nomObra VARCHAR(60) NOT NULL,
    fecObra DATETIME NOT NULL,
    CONSTRAINT PK_OBRAS PRIMARY KEY (codObra),
    CONSTRAINT FK_OBRAS_ESTILOS FOREIGN KEY (codEstilo)
        REFERENCES ESTILOS (codEstilo)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_OBRAS_ARTISTAS FOREIGN KEY (codArtista)
        REFERENCES ARTISTAS (codArtista)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_OBRAS_TIPOoBRAS FOREIGN KEY (codTipoO)
        REFERENCES TIPOoBRAS (codTipoO)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_OBRAS_SALAS FOREIGN KEY (codSala)
        REFERENCES SALAS (codSala)
        ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLEADOS (
    codEmpleado VARCHAR(30) NOT NULL,
    nomEmpleado VARCHAR(60) NOT NULL,
    edaEmpleado INT NULL,
    telefonoEmpleado VARCHAR(10) NULL,
    fecNacim DATETIME NULL,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (codEmpleado)
);

CREATE TABLE IF NOT EXISTS RESTAURADORES (
    codEmpleado VARCHAR(30) NOT NULL,
    codRestau VARCHAR(30) NOT NULL,
    sueldo DECIMAL(6 , 2 ) NOT NULL,
    CONSTRAINT PK_RESTAURADORES PRIMARY KEY (codRestau),
    CONSTRAINT FK_RESTAURADORES_EMPLEADOS FOREIGN KEY (codEmpleado)
        REFERENCES EMPLEADOS (codEmpleado)
        ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SEGURIDAD (
    codSala VARCHAR(30) NOT NULL,
    codEmpleado VARCHAR(30) NOT NULL,
    codSeguri VARCHAR(30) NOT NULL,
    sueldo DECIMAL(6 , 2 ) NOT NULL,
    CONSTRAINT PK_SEGURIDAD PRIMARY KEY (codSeguri),
    CONSTRAINT FK_SEGURIDAD_EMPLEADOS FOREIGN KEY (codEmpleado)
        REFERENCES EMPLEADOS (codEmpleado)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_SEGURIDAD_SALAS FOREIGN KEY (codSala)
        REFERENCES SALAS (codSala)
        ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS RESTAURACIONES (
    codObra VARCHAR(30) NOT NULL,
    codRestau VARCHAR(30) NOT NULL,
    fecIniRest DATETIME NOT NULL,
    fecFinRest DATETIME NOT NULL,
    observaciones VARCHAR(100) NULL,
    CONSTRAINT PK_RESTAURACIONES PRIMARY KEY (codObra , codRestau),
    CONSTRAINT FK_RESTAURACIONES_OBRAS FOREIGN KEY (codObra)
        REFERENCES OBRAS (codObra)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_RESTAURACIONES_RESTAURADORES FOREIGN KEY (codRestau)
        REFERENCES RESTAURADORES (codRestau)
        ON DELETE NO ACTION ON UPDATE CASCADE
);