drop database if exists centrocomercial;
create database if	not exists CENTROCOMERCIAL;
use CENTROCOMERCIAL;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
    numEmpleado VARCHAR(30) NOT NULL,
    extelefon VARCHAR(4) NULL,
    fecNacim DATETIME NULL,
    fecIngreso DATETIME NULL,
    salario DECIMAL(6 , 2 ) unsigned NOT NULL,
    comision DECIMAL(4 , 2 )  unsigned not null,
    numHijos INT NULL,
    nomemp VARCHAR(60) NOT NULL,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (numEmpleado)
);


CREATE TABLE IF NOT EXISTS CENTROS (
    numCentro VARCHAR(30) NOT NULL,
    nomCentro VARCHAR(60) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CENTROS PRIMARY KEY (numCentro)
);

CREATE TABLE IF NOT EXISTS DEPTOS (
    numDepto VARCHAR(30) NOT NULL,
    numCentro VARCHAR(30) NOT NULL,
    presupuesto DECIMAL(10 , 2 ) NULL,
    nomDepto VARCHAR(30) NOT NULL,
    idDepe VARCHAR(30) NULL,
    CONSTRAINT PK_DEPTOS PRIMARY KEY (numDepto , numCentro),
    CONSTRAINT FK_DEPTOS_CENTROS FOREIGN KEY (numCentro)
        REFERENCES CENTROS (numCentro)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_DEPTOS_DEPENDE FOREIGN KEY (idDepe)
        REFERENCES DEPTOS (numDepto)
        ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DIRIGEN (
    numEmpleado VARCHAR(30) NOT NULL,
    numDepto VARCHAR(30) NOT NULL,
    numCentro VARCHAR(30) NOT NULL,
    fecIniDir DATETIME NOT NULL,
    fecFinDir DATETIME NOT NULL,
    CONSTRAINT PK_DIRIGEN PRIMARY KEY (numEmpleado , numDepto , numCentro),
    CONSTRAINT FK_DIRIGEN_EMPLEADOS FOREIGN KEY (numEmpleado)
        REFERENCES EMPLEADOS (numEmpleado)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_DIRIGEN_DEPTOS FOREIGN KEY (numDepto , numCentro)
        REFERENCES DEPTOS (numDepto , numCentro)
        ON DELETE NO ACTION ON UPDATE CASCADE
);